server:
  port: 8000
  session-timeout : 30
  tomcat.max-threads: 0
  tomcat.url-encoding : UTF-8

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hero
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  devtools:
    restart:
      additional-paths: src/main/java
      exclude: static

web:
  upload-path: D:/workspace/idea/hero/src/main/resources/static/


